// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchIPadPro11Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchIPadPro11() {
    driver.get("https://www.bestbuy.ca/en-ca");
    driver.manage().window().setSize(new Dimension(820, 860));
    assertThat(driver.getTitle(), is("Best Buy: Shop Online For Deals & Save | Best Buy Canada"));
    driver.findElement(By.name("search")).click();
    {
      WebElement element = driver.findElement(By.name("search"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    driver.findElement(By.name("search")).sendKeys("ipad pro 11");
    driver.findElement(By.name("search")).sendKeys(Keys.ENTER);
    assertThat(driver.getTitle(), is("Results for: ipad pro 11 | Best Buy Canada"));
    driver.findElement(By.cssSelector(".breadcrumb_iafPH > li:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".breadcrumb_iafPH > li:nth-child(2)")).getText(), is("Search for \\\"ipad pro 11\\\""));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col-xs-12_198le:nth-child(1) .productItemName_3IZ3c"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(1) .productItemName_3IZ3c")).click();
    assertThat(driver.getTitle(), is("Apple iPad Pro 11\" 128GB with Wi-Fi (3rd Generation) - Space Grey | Best Buy Canada"));
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(4) .x-crumb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".x-page-content")).click();
    assertThat(driver.findElement(By.cssSelector(".productName_2KoPa")).getText(), is("Apple iPad Pro 11\\\" 128GB with Wi-Fi (3rd Generation) - Space Grey"));
  }
}
