// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DealsFullPathTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dealsFullPath() {
    driver.get("https://www.bestbuy.ca/en-ca");
    driver.manage().window().setSize(new Dimension(1556, 1232));
    driver.findElement(By.cssSelector("li:nth-child(3) button > span")).click();
    driver.findElement(By.cssSelector(".flyoutMenu_2DHKo:nth-child(3) .menuItem_2kIs9:nth-child(3) .menuItemText_1yd__")).click();
    js.executeScript("window.scrollTo(0,472)");
    js.executeScript("window.scrollTo(0,1502)");
    js.executeScript("window.scrollTo(0,2433)");
    js.executeScript("window.scrollTo(0,3115)");
    js.executeScript("window.scrollTo(0,4041)");
    js.executeScript("window.scrollTo(0,4499)");
    driver.findElement(By.cssSelector(".button_1Yg9v > .content_3Dbgg")).click();
    js.executeScript("window.scrollTo(0,6324)");
    driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(29) .productItemName_3IZ3c")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
