// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchByBrandsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void brandsAlphabeticalPath() {
    driver.get("https://www.bestbuy.ca/en-ca");
    driver.manage().window().maximize();
    driver.findElement(By.cssSelector("li:nth-child(2) button > span")).click();
    try {
      driver.findElement(By.linkText("JBL")).click(); // check point after new page
    } catch (NoSuchElementException e) {
      fail("Cannot find JBL link.");
    }

    js.executeScript("window.scrollTo(0,222)");
    try {
      driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(6) .productItemName_3IZ3c")).click(); // check point after new page
    } catch (NoSuchElementException e) {
      fail("Cannot find JBL Flip 5");
    }

    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
  }

  @Test
  public void brandsIdealPath() {
    driver.get("https://www.bestbuy.ca/en-ca");
    driver.manage().window().maximize();
    driver.findElement(By.cssSelector("li:nth-child(2) button > .white_3qh7k")).click();
    try {
      driver.findElement(By.linkText("JBL")).click();
      {
        WebElement element = driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(1) .container_2eR50"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
    } catch (NoSuchElementException e) {
      fail("Could not find JBL.");
    }
    js.executeScript("window.scrollTo(0,391)");
    {
      WebElement element = driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(2) .productItemName_3IZ3c"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(6) .sliderTarget_2Q87g:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    try {
      driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(6) .sliderTarget_2Q87g:nth-child(1)")).click(); 
    } catch (NoSuchElementException e) {
      fail("Could not find JBL Flip 5.");
    }
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,1)");
  }

}
